### ISSUE TITLE
sam2lca analyze error

### ISSUE THREAD

**Issue by wyc661217** [maxibor/sam2lca#12]
Dear Maxime,

I am trying to set up a test run using sam2lca for lca inference, and keep getting the following error messages:

Step 1/7: Loading taxonomy database
Traceback (most recent call last):
  File "/opt/anaconda3/bin/sam2lca", line 10, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/sam2lca/cli.py", line 140, in analyze
    sam2lca(**kwargs, **ctx.obj)
  File "/opt/anaconda3/lib/python3.9/site-packages/sam2lca/main.py", line 76, in sam2lca
    al = Alignment(al_file=sam, nb_steps=nb_steps)
  File "/opt/anaconda3/lib/python3.9/site-packages/sam2lca/parse_alignment.py", line 55, in __init__
    for ref_stat in alignment.get_index_statistics():
AttributeError: 'pysam.calignmentfile.AlignmentFile' object has no attribute 'get_index_statistics'

The case is quite simple where my input bam files are generated by first bowtie2 mapping QCed reads against NCBI-nt and refseq, then merging the bam files and sort with samtools. The code for sam2lca is:

sam2lca analyze -t ncbi -a nucl SPL_153_7001.q_sorted.bam 

I tried both with bam file sorted by qname, and sorted by coordinates and then indexed by samtools index. It seems to have some inconsistence with the pysam where there is no required index statistics available. Could you help to point what went wrong?

An example bam file (sorted by qname) can be download from https://sid.erda.dk/share_redirect/bO3s40dU3T

Thank you very much!

**Comment by maxibor** [comment]
Hey @wyc661217 ,
I can not download your test file, maybe you have another place to put it ?
You can also attach files directly on github, provided that they're small enough.

**Comment by wyc661217** [comment]
It's 600+ MB and too big for GitHub. I uploaded it to google drive at here: https://drive.google.com/drive/folders/1_yV0uyOk-2W1m1lur0s-bf1SKiPDnzaA?usp=sharing. Thank you!

**Comment by maxibor** [comment]
Can you please subsample it to a more manageable size ?
You can use [samtools](http://www.htslib.org/doc/samtools-view.html) view for that 
`samtools view --subsample 0.05 -b yourfile.bam > subsampled.bam`

**Comment by wyc661217** [comment]
Can I have your samtools version? I have tried v1.3.1, v1.10, and v1.15.1. All got the same error as in the initial post.

Seems it failed at the 1/7 step when reading in the taxonomy database, since I never get into the Step 2/7: Loading acc2tax database?

**Comment by maxibor** [comment]
Hey @wyc661217 
From your error log, this is failing because your bam file is not proporly indexed by samtools, which sam2lca needs to fetch the taxonomic IDs.

I'm using samtools v1.15.1, and with a fresh install of samtools and sam2lca in a dedicated conda environment (attached below), this works fine.

```bash
$ samtools sort -@ 8 SPL_153_7001.sort.bam > SPL_153_7001.sorted.bam
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
$ samtools index -c SPL_153_7001.sorted.bam
$ sam2lca analyze -a nucl SPL_153_7001.sorted.bam
Step 1/7: Loading taxonomy database
Step 2/7: Loading acc2tax database
Step 3/7: Converting accession numbers to TAXIDs
100%|████████████████████████████████████| 2345172/2345172 [01:37<00:00, 24155.54it/s]
Step 4/7: Parsing reads in alignment file
100%|████████████████████████████████| 8494599/8494599 [00:28<00:00, 302931.82reads/s]
Step 5/7: Assigning LCA to reads
100%|████████████████████████████████████████████| 9447/9447 [00:47<00:00, 197.44it/s]
Step 6/7: Converting TAXIDs to taxonomic lineages
100%|██████████████████████████████████████████| 1701/1701 [00:00<00:00, 23887.77it/s]
100%|█████████████████████████████████████████| 4501/4501 [00:00<00:00, 174301.19it/s]
Step 7/7: writing sam2lca results:
* JSON to SPL_153_7001.sorted.sam2lca.json
* CSV to SPL_153_7001.sorted.sam2lca.csv
```

[environment.yaml.zip](https://github.com/maxibor/sam2lca/files/8851869/environment.yaml.zip)

**Comment by maxibor** [comment]
Did it work for you with the dedicated environment @wyc661217 ?

**Comment by wyc661217** [comment]
Yes, I got it work on another cloud by reinstalling everything. Thank you very much!
