### ISSUE TITLE
Consider adding of creating otu tables of given taxonomic rank

### ISSUE THREAD

**Issue by jfy133** [maxibor/sam2lca#2]
After performing LCA, one of the most common procedures is to generate taxonomy/otu tables.

Maybe we can consider adding a auxiliary script or function that allows generation of these, as in most cases you would want to make the otu table at a given taxonomic rank (E.g. report only genus level assignments).

 Therefore it would be suitable for this package somewhat, as you are already querying the taxonomic map.

**Comment by maxibor** [comment]
It was there, but not yet documented. I've updated the docs with 238d778
